name: Try to expand local template using cargo-template
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mytemplate
    steps:
      - uses: actions/checkout@v3
      - name: "Define values"
        run: |
          cat <<'EOF' > template-values.txt
          [values]
          repo-name = "test-rust-cli"
          project-description = "does some stuff"
          author-name = "Nathan Henrie"
          email = "foo@bar.com"
          EOF
      - uses: cargo-generate/cargo-generate-action@v0.18.3
        with:
          name: ${{ env.PROJECT_NAME }}
          template_values_file: ./template-values.txt
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs would fail
      # see https://github.com/rust-lang/cargo/issues/9922
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
